---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Mess with clickhouse distrib
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib (rescue)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: "0644"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers to restart clickhouse
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      become: true
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install vector
  hosts: clickhouse
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
        mode: "0644"
      notify: Start vector service
    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name:
          - vector-{{ vector_version }}.rpm
    - name: Flush handlers to restart vector
      ansible.builtin.meta: flush_handlers
- name: Install lighthouse
  hosts: lighthouse
  tags: lighthouse
  handlers:
    - name: restarted nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: not ansible_check_mode
  tasks:
    - block:
      - name: add repo nginx
        become: true
        ansible.builtin.copy:
          dest: /etc/yum.repos.d/nginx.repo
          mode: '0755'
          content: |
            [nginx]
            name=nginx repo
            baseurl=https://nginx.org/packages/centos/$releasever/$basearch/
            gpgcheck=0
            enabled=1
      - name: install nginx and git
        become: true
        ansible.builtin.yum:
          name:
            - nginx
            - git
          state: latest
          update_cache: yes
        when: not ansible_check_mode
      - name: Get lighthouse from git
        become: true
        ansible.builtin.git:
          repo: 'https://github.com/VKCOM/lighthouse.git'
          dest: "{{ lighthouse_home_dir }}"
        when: not ansible_check_mode
      - name: Configure nginx from template
        ansible.builtin.template:
          src: lighthouse.conf.j2
          dest: "{{ nginx_config_dir }}/conf.d/default.conf"
        become: true
        notify: restarted nginx service
      - name: Flush handlers
        meta: flush_handlers
